# Generated by Django 4.1.5 on 2023-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_column', models.CharField(max_length=100)),
                ('i_column', models.CharField(max_length=100)),
                ('n_column', models.CharField(max_length=100)),
                ('g_column', models.CharField(max_length=100)),
                ('o_column', models.CharField(max_length=100)),
            ],
        ),
    ]
