# Generated by Django 4.1.5 on 2023-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_column', models.CharField(max_length=100)),
                ('i_column', models.CharField(max_length=100)),
                ('n_column', models.CharField(max_length=100)),
                ('g_column', models.CharField(max_length=100)),
                ('o_column', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('ticket_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
