# Generated by Django 4.1.5 on 2023-09-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoNumber',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bingo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BingoCard',
        ),
    ]
