# Generated by Django 4.1.5 on 2023-09-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_bingonumber_delete_bingocard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bingonumber',
            old_name='date',
            new_name='date_drawn',
        ),
        migrations.AddField(
            model_name='bingonumber',
            name='is_drawn',
            field=models.BooleanField(default=False),
        ),
    ]
