# Generated by Django 4.1.5 on 2023-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleentry',
            name='solicitor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='solicitor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
