# Generated by Django 4.1.5 on 2023-09-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_date_bingonumber_date_drawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='date_drawn',
            field=models.DateTimeField(null=True),
        ),
    ]
