# Generated by Django 4.1.5 on 2023-09-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_bingonumber_date_drawn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bingonumber',
            old_name='date_drawn',
            new_name='time_drawn',
        ),
    ]
