# Generated by Django 4.1.5 on 2023-09-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_date_drawn_bingonumber_time_drawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='time_drawn',
            field=models.TimeField(null=True),
        ),
    ]
