# Generated by Django 4.1.5 on 2023-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_bingonumber_time_drawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='ticket_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='winner',
            name='ticket_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
