# Generated by Django 4.1.5 on 2023-09-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_raffleentry_ticket_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffleentry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='address',
        ),
    ]
